#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiHBM.Controllers
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HANSAMobileBusinessPRDAndroid02")]
	public partial class DbHBM02DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public DbHBM02DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HANSAMobileBusinessPRDAndroid02ConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DbHBM02DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbHBM02DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbHBM02DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbHBM02DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.hsp_ObtenerClientesHBM")]
		public ISingleResult<hsp_ObtenerClientesHBMResult> hsp_ObtenerClientesHBM([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string p_kunnr)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_kunnr);
			return ((ISingleResult<hsp_ObtenerClientesHBMResult>)(result.ReturnValue));
		}
	}
	
	public partial class hsp_ObtenerClientesHBMResult
	{
		
		private string _NITCliente;
		
		private string _IdRegimenTribut;
		
		private string _TipoDocIdentificacion;
		
		private string _DireccionCli;
		
		private string _TipoCliente;
		
		private string _RazonSocialCli;
		
		private string _Poblacion;
		
		private string _TelefonoCli;
		
		private string _IdRegion;
		
		private string _ZonaTransporte;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
		public hsp_ObtenerClientesHBMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NITCliente", DbType="NVarChar(16)")]
		public string NITCliente
		{
			get
			{
				return this._NITCliente;
			}
			set
			{
				if ((this._NITCliente != value))
				{
					this._NITCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegimenTribut", DbType="NVarChar(4)")]
		public string IdRegimenTribut
		{
			get
			{
				return this._IdRegimenTribut;
			}
			set
			{
				if ((this._IdRegimenTribut != value))
				{
					this._IdRegimenTribut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoDocIdentificacion", DbType="NVarChar(40)")]
		public string TipoDocIdentificacion
		{
			get
			{
				return this._TipoDocIdentificacion;
			}
			set
			{
				if ((this._TipoDocIdentificacion != value))
				{
					this._TipoDocIdentificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DireccionCli", DbType="NVarChar(60)")]
		public string DireccionCli
		{
			get
			{
				return this._DireccionCli;
			}
			set
			{
				if ((this._DireccionCli != value))
				{
					this._DireccionCli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCliente", DbType="NVarChar(10)")]
		public string TipoCliente
		{
			get
			{
				return this._TipoCliente;
			}
			set
			{
				if ((this._TipoCliente != value))
				{
					this._TipoCliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RazonSocialCli", DbType="NVarChar(40)")]
		public string RazonSocialCli
		{
			get
			{
				return this._RazonSocialCli;
			}
			set
			{
				if ((this._RazonSocialCli != value))
				{
					this._RazonSocialCli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Poblacion", DbType="NVarChar(40)")]
		public string Poblacion
		{
			get
			{
				return this._Poblacion;
			}
			set
			{
				if ((this._Poblacion != value))
				{
					this._Poblacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelefonoCli", DbType="NVarChar(30)")]
		public string TelefonoCli
		{
			get
			{
				return this._TelefonoCli;
			}
			set
			{
				if ((this._TelefonoCli != value))
				{
					this._TelefonoCli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRegion", DbType="NVarChar(6)")]
		public string IdRegion
		{
			get
			{
				return this._IdRegion;
			}
			set
			{
				if ((this._IdRegion != value))
				{
					this._IdRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZonaTransporte", DbType="NVarChar(40)")]
		public string ZonaTransporte
		{
			get
			{
				return this._ZonaTransporte;
			}
			set
			{
				if ((this._ZonaTransporte != value))
				{
					this._ZonaTransporte = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this._FechaModificacion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
