<?xml version="1.0" encoding="utf-8"?><Database Name="HANSAMobileBusinessPRDAndroid02" Class="DbHBM02DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=HANNACBDP01;Initial Catalog=HANSAMobileBusinessPRDAndroid02;Persist Security Info=True;User ID=USERWEB_PRD" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HANSAMobileBusinessPRDAndroid02ConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.hsp_ObtenerClientesHBM" Method="hsp_ObtenerClientesHBM">
    <Parameter Name="p_kunnr" Type="System.String" DbType="NVarChar(10)" />
    <ElementType Name="hsp_ObtenerClientesHBMResult">
      <Column Name="NITCliente" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IdRegimenTribut" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="TipoDocIdentificacion" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="DireccionCli" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="TipoCliente" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="RazonSocialCli" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Poblacion" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="TelefonoCli" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="IdRegion" Type="System.String" DbType="NVarChar(6)" CanBeNull="true" />
      <Column Name="ZonaTransporte" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="FechaModificacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>