name: Build and Deploy .NET Web Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.x'  # O '7.0.x' si usas .NET 7
  PROJECT_PATH: 'src/WebApiHBM/WebApiHBM.csproj'
  PUBLISH_FOLDER: 'publish'
  SERVER: 'hannacwebq01'
  DEPLOY_PATH: 'C:\inetpub\wwwroot\MiServicioWeb'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Verify project structure
      run: |
        ls -Recurse -File
        echo "PROJECT_PATH: ${{ env.PROJECT_PATH }}"
        Test-Path ${{ env.PROJECT_PATH }} -PathType Leaf

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --configuration Release --no-build --no-restore

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_FOLDER }} --no-restore

    - name: Zip artifacts
      run: |
        Compress-Archive -Path ${{ env.PUBLISH_FOLDER }}\* -DestinationPath publish.zip
        Write-Output "ARTIFACT_NAME=publish.zip" >> $env:GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-app
        path: publish.zip

  deploy:
    needs: build
    runs-on: windows-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: web-app

    - name: Deploy to Hannacwebq01
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.SERVER }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "publish.zip"
        target: ${{ env.DEPLOY_PATH }}

    - name: Unzip and deploy on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd ${{ env.DEPLOY_PATH }}
          Expand-Archive -Path publish.zip -DestinationPath . -Force
          Remove-Item publish.zip
          iisreset
