name: Build and Deploy WebApiHBM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.x'  # O '8.0.x' si prefieres .NET 8
  PUBLISH_FOLDER: 'publish'
  SERVER: 'http://hannacwebq01.sismovil.com.bo/'
  DEPLOY_PATH: 'C:\inetpub\wwwroot\WebApiHBM_prueba'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Verify repository structure
      run: |
        ls -Recurse
        echo "Current directory: $(Get-Location)"

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Find project file
      id: find-project
      run: |
        $project = Get-ChildItem -Recurse -Filter *.csproj | Select-Object -First 1
        if (-not $project) {
          Write-Error "No .csproj file found in repository"
          exit 1
        }
        echo "PROJECT_PATH=$($project.FullName)" >> $env:GITHUB_ENV
        echo "Found project at: $($project.FullName)"

    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Fix project file
      run: |
        (Get-Content WebApiHBM.csproj) -replace 
          '<Import Project="\$\(VSToolsPath\)\\WebApplications\\Microsoft\.WebApplication\.targets" />',
          '<Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk.Web" />' | 
          Set-Content WebApiHBM.csproj
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --configuration Release --no-build --no-restore

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_FOLDER }} --no-restore

    - name: Zip artifacts
      run: |
        Compress-Archive -Path ${{ env.PUBLISH_FOLDER }}\* -DestinationPath publish.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-app
        path: publish.zip

  deploy:
    needs: build
    runs-on: windows-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: web-app

    - name: Deploy to Hannacwebq01
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.SERVER }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "publish.zip"
        target: ${{ env.DEPLOY_PATH }}

    - name: Unzip and deploy on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.SERVER }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          cd ${{ env.DEPLOY_PATH }}
          Expand-Archive -Path publish.zip -DestinationPath . -Force
          Remove-Item publish.zip
          iisreset
